### ISSUE TITLE
Error uploading SEAI BER Public Search data

### ISSUE THREAD

**Issue by oisindoherty3** [energy-modelling-ireland/ibsg#3]
I used the SEAI's BER Public Search tool https://ndber.seai.ie/BERResearchTool/ber/search.aspx and used the download file from there to upload in zip format. Upon doing this I received the error - "Whoops — something went wrong! An error has been logged."

![ber_error](https://user-images.githubusercontent.com/69256705/124748979-9ca37080-df1b-11eb-8d80-2ddd6f17a327.PNG)

It appears the way around this is to install 7zip and upload the csv.gz file as a zip file and use that as the input dataset.

**Comment by rdmolony** [comment]
Cheers Oisin!  The issue here is that the `Drag and drop file here` widget only expects zipped `Small Area BERs`  (which are available upon special request from the SEAI) and not the zipped `BER Public` dataset.  As a result it doesn't understand the column names and so cannot read the dataset.  If you want to filter the `BER Public` dataset click `Fetch Postcode BERs` - I'll add more explanation to the introductory guide at the top of the app!
